### ISSUE TITLE
Correct usage description

### ISSUE THREAD

**Issue by datenreisender** [alexbepple/simplify-url#6]
In https://github.com/alexbepple/simplify-url/blob/master/README.md#usage it is described that this script simplifies „the URL that is on the system clipboard“, which obviously isn't true anymore since 7abf03a7c74354a46b15616eba2d8ff65ada8ed1. So the rest of the paragraph is also obsolete. 

Please correct the mentioned paragraph and maybe also include a description how it now can be used with Alfred. 

I now use a workflow that calls the script as 

    simplify.url.rb "`pbpaste`" | pbcopy

Do you know a better way?

**Comment by datenreisender** [comment]
Little addendum: The script above has the disadvantage of always ending the entry on the clipboard with a line break. Because of that I changed my script to 
```sh
readonly simplified_url=$(~/bin/simplify.url.rb "$(pbpaste)")
printf $simplified_url | pbcopy
```

**Comment by alexbepple** [comment]
I have an Alfred workflow that uses Alfred’s facilities to work with the clipboard. This does not introduce unnecessary linebreaks.
<img width="789" alt="screen shot 2015-07-07 at 22 45 26" src="https://cloud.githubusercontent.com/assets/159355/8556849/f6bcf2c2-24f9-11e5-9905-38b0ce0e6bf8.png">
<img width="518" alt="screen shot 2015-07-07 at 22 45 36" src="https://cloud.githubusercontent.com/assets/159355/8556852/fbc2f0a0-24f9-11e5-865d-3d1f7ad2f274.png">
<img width="655" alt="screen shot 2015-07-07 at 22 45 49" src="https://cloud.githubusercontent.com/assets/159355/8556856/fee96a34-24f9-11e5-8d91-cb62107ee88a.png">

**Comment by datenreisender** [comment]
Thanks for the idea to use the Alfred workflow elements to query and fill the clipboard.
